### ISSUE TITLE
API doesn't support `CONJUR_VERSION` env var

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-go#16]
The Go API currently supports the `CONJUR_MAJOR_VERSION` method of specifying the Conjur version, but it should be updated to support the `CONJUR_VERSION` method as well to be consistent with the naming convention elsewhere. Support for `CONJUR_MAJOR_VERSION` should be maintained in order to ensure backwards compatibility.

**Comment by doodlesbykumbi** [comment]
addressed in https://github.com/cyberark/conjur-api-go/pull/19
