### ISSUE TITLE
update dependency github.com/alessio/shellescape

### ISSUE THREAD

**Issue by tribock** [cyberark/conjur-api-go#182]
## Summary

when running go get -u ./... the following error occurs:

`go get -u github.com/cyberark/conjur-api-go/conjurapi
go: github.com/alessio/shellescape@v1.5.1: parsing go.mod:
        module declares its path as: al.essio.dev/pkg/shellescape
                but was required as: github.com/alessio/shellescape`

## Steps to Reproduce

1. go get -u github.com/cyberark/conjur-api-go/conjurapi

## Expected Results

no errors and no warnings

## Actual Results

`go: github.com/alessio/shellescape@v1.5.1: parsing go.mod:
        module declares its path as: al.essio.dev/pkg/shellescape
                but was required as: github.com/alessio/shellescape
        trying github.com/alessio/shellescape@v1.5.1-rc1
go: github.com/alessio/shellescape@v1.5.1-rc1: parsing go.mod:
        module declares its path as: al.essio.dev/pkg/shellescape
                but was required as: github.com/alessio/shellescape
        trying github.com/alessio/shellescape@v1.5.0
go: github.com/alessio/shellescape@v1.5.0: parsing go.mod:
        module declares its path as: al.essio.dev/pkg/shellescape
                but was required as: github.com/alessio/shellescape
        trying github.com/alessio/shellescape@v1.5.0-rc1
go: github.com/alessio/shellescape@v1.5.0-rc1: parsing go.mod:
        module declares its path as: al.essio.dev/pkg/shellescape
                but was required as: github.com/alessio/shellescape
        restoring github.com/alessio/shellescape@v1.4.2`

## Reproducible

   * [x ] Always 

   
## Version/Tag number

github.com/cyberark/conjur-api-go v0.12.4

**Comment by szh** [comment]
Hey @tribock, thanks for reporting this. Do you want to submit a PR for this?

**Comment by szh** [comment]
I'm working on a fix for this right now and it'll be included in the next release.
